include(CheckIncludeFile)
include(CheckFunctionExists)
include(CheckCSourceCompiles)
include(CheckLibraryExists)
include(CheckSymbolExists)
include(CheckStructHasMember)

check_function_exists(cpuset_setaffinity HAVE_CPUSET_SETAFFINITY)
check_function_exists(sched_setaffinity HAVE_SCHED_SETAFFINITY)
check_function_exists(SetProcessAffinityMask HAVE_SETPROCESSAFFINITYMASK)

check_function_exists(clock_gettime HAVE_CLOCK_GETTIME)
check_function_exists(daemon HAVE_DAEMON)
check_function_exists(getline HAVE_GETLINE)
check_function_exists(sendfile HAVE_SENDFILE)

check_include_file(dlfcn.h HAVE_DLFCN_H)
check_include_file(inttypes.h HAVE_INTTYPES_H)
check_include_file(memory.h HAVE_MEMORY_H)
check_include_file(stdint.h HAVE_STDINT_H)
check_include_file(stdlib.h HAVE_STDLIB_H)
check_include_file(string.h HAVE_STRING_H)
check_include_file(strings.h HAVE_STRINGS_H)
check_include_file(poll.h HAVE_POLL_H)
check_include_file(endian.h HAVE_ENDIAN_H)
check_include_file("sys/endian.h" HAVE_SYS_ENDIAN_H)
check_include_file("sys/socket.h" HAVE_SYS_SOCKET_H)
check_include_file("sys/stat.h" HAVE_SYS_STAT_H)
check_include_file("sys/types.h" HAVE_SYS_TYPES_H)
check_include_file(unistd.h HAVE_UNISTD_H)

check_symbol_exists(IPV6_FLOWLABEL_MGR "linux/in6.h" HAVE_FLOWLABEL)
check_symbol_exists(SO_MAX_PACING_RATE "sys/socket.h" HAVE_SO_MAX_PACING_RATE)
check_symbol_exists(TCP_CONGESTION "netinet/tcp.h" HAVE_TCP_CONGESTION)

check_symbol_exists(IP_MTU_DISCOVER "netinet/ip.h" HAVE_DONT_FRAGMENT)
check_symbol_exists(IP_DONTFRAG "netinet/ip.h" HAVE_IP_DONTFRAG)
check_symbol_exists(IP_DONTFRAGMENT "netinet/ip.h" HAVE_IP_DONTFRAGMENT)
check_symbol_exists(IP_MTU_DISCOVER "netinet/ip.h" HAVE_IP_MTU_DISCOVER)
check_symbol_exists(SO_BINDTODEVICE "sys/socket.h" HAVE_SO_BINDTODEVICE)
check_symbol_exists(SO_MAX_PACING_RATE "sys/socket.h" HAVE_SO_MAX_PACING_RATE)

check_include_file("linux/tcp.h" HAVE_LINUX_TCP_H)
check_struct_has_member("struct tcp_info" tcpi_snd_wnd HAVE_TCP_INFO_SND_WND "linux/tcp.h")
check_symbol_exists(SO_MAX_PACING_RATE "sys/socket.h" HAVE_TCP_USER_TIMEOUT)

find_library(MATH m REQUIRED)

find_library(PTHREAD pthread REQUIRED)
if (PTHREAD)
    check_include_file(pthread.h HAVE_PTHREAD)
    check_symbol_exists(PTHREAD_PRIO_INHERIT pthread.h HAVE_PTHREAD_PRIO_INHERIT)
    check_symbol_exists(PTHREAD_CREATE_JOINABLE pthread.h PTHREAD_CREATE_JOINABLE)   
endif ()

if (HAVE_DLFCN_H AND HAVE_INTTYPES_H AND HAVE_MEMORY_H AND HAVE_STDINT_H AND HAVE_STDLIB_H AND HAVE_STRING_H AND HAVE_STRINGS_H)
    set(STDC_HEADERS 1 CACHE INTERNAL "ANSI C header files")
else ()
    message(STATUS "ANSI C header files - not found")
    set(STDC_HEADERS 0 CACHE INTERNAL "ANSI C header files")
endif ()

if (HAVE_CPUSET_SETAFFINITY OR HAVE_SCHED_SETAFFINITY OR HAVE_SETPROCESSAFFINITYMASK)
    set(HAVE_CPU_AFFINITY 1 CACHE INTERNAL "CPU affinity support")
else ()
    message(STATUS "Have CPU affinity support - not found")
    set(HAVE_CPU_AFFINITY 0 CACHE INTERNAL "CPU affinity support")
endif ()